# Generated by Django 5.0 on 2024-03-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedetails",
            name="length",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamedetails",
            name="winning_team",
            field=models.CharField(
                choices=[("Blue", "Blue"), ("Red", "Red")], default=1, max_length=10
            ),
            preserve_default=False,
        ),
    ]
