# Generated by Django 5.0 on 2024-03-01 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vods", "0002_gamedetails_length_gamedetails_winning_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedetails",
            name="vod",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="vods.vod"
            ),
            preserve_default=False,
        ),
    ]
