# Generated by Django 5.0 on 2024-03-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vods", "0003_gamedetails_vod"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamedetails",
            options={"verbose_name_plural": "Game Details"},
        ),
        migrations.AlterField(
            model_name="vod",
            name="tags",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owcs", "Overwatch Championship Series"),
                    ("owl", "Overwatch League"),
                    ("owcn", "Overwatch Contenders"),
                    ("NA", "North America"),
                    ("EU", "Europe"),
                    ("EMEA", "Europe, Middle East, and Africa"),
                    ("TANK", "Tank"),
                    ("DPS", "Damage"),
                    ("SUP", "SUPPORT"),
                    ("Circus", "Circus"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
